spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/food;
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
  servlet:
    multipart:
      enabled: true
  jwt:
    secret: "y=6uh6#!^$_z0ih@to&c5_wpnf?7lw+k9b)rca!ief2iu2v(0"

flask:
  url: "input flask url"

logging:
  level:
    org.hibernate.SQL: debug
    org.springframework: debug
    org.springframework.web: debug